/**
 * SolenOS Care Continuity System — core product contract.
 * NOT a note app, chatbot, or symptom tracker.
 */

export const CARE_CONTINUITY_SYSTEM_GOAL =
  "Replace caregiver memory with an external, continuously structured care history — reducing mental and cognitive overload.";

export const CARE_CONTINUITY_ONE_LINE_TRUTH =
  "Everything becomes a node in one evolving Continuity Graph — structured reality over time, not answers or chat.";

export const CARE_CONTINUITY_PROHIBITED = [
  "assign urgency without required data",
  "assume outcomes",
  "downplay missing information",
  "hallucinate diagnoses or causes",
  "treat uncertainty as low risk",
  "store documents in isolation without structured events",
  "keyword search as memory replacement",
  "guess missing information",
] as const;

/** MVP implementation order — all pillars must exist. */
export const CARE_CONTINUITY_MVP_PILLARS = [
  "continuity_graph",
  "care_journey_event_model",
  "document_structured_extraction",
  "timeline_view",
  "relationship_linking",
  "memory_reconstruction",
  "meeting_preparation",
  "uncertainty_framework",
  "memory_layers",
  "failure_resilience",
  "trust_provenance",
  "network_effect_moat",
  "success_model",
  "final_output_contract",
  "mvp_surface_area",
  "continuous_execution_loop",
  "behavior_interpretation_engine",
  "continuity_decay_engine",
  "north_star_experience",
  "architectural_boundaries",
  "clarification_engine",
  "memory_strategy_engine",
  "trust_layer_engine",
  "crisis_mode_interaction_layer",
  "multi_caregiver_context_model",
  "audit_trail_system",
  "state_of_care_summary_engine",
  "care_context_diff_engine",
  "entry_behavior_protocol",
  "care_timeline_engine",
  "task_extraction_system",
  "current_state_view_engine",
  "forbidden_build_zone",
  "adoption_wedge_engine",
  "product_reality_model",
  "policy_engine",
  "contradiction_detection_engine",
  "timeline_reconstruction_engine",
  "care_transparency_layer",
  "baseline_intelligence_engine",
  "care_reality_profile_engine",
  "moment_of_need_engine",
  "retention_engine",
  "priority_resolution_system",
  "event_sourced_storage",
  "engine_execution_contract",
  "edge_state_machine",
  "confidence_calibration_system",
  "care_state_engine",
  "single_user_journey",
  "product_north_star",
  "product_constitution",
] as const;

export type CareContinuityPillar = (typeof CARE_CONTINUITY_MVP_PILLARS)[number];

export const PILLAR_MODULES: Record<CareContinuityPillar, string> = {
  continuity_graph: "src/lib/continuity-graph",
  care_journey_event_model: "src/lib/care-journey-graph",
  document_structured_extraction: "src/lib/universal-knowledge-extraction",
  timeline_view: "src/components/ops-devtools/CareJourneyTimelinePanel.tsx",
  relationship_linking: "src/lib/care-journey-graph/detect-relationships.ts",
  memory_reconstruction: "src/lib/memory-reconstruction-engine",
  meeting_preparation: "src/lib/meeting-preparation",
  uncertainty_framework: "src/lib/risk-uncertainty-engine",
  memory_layers: "src/lib/care-memory-layers",
  failure_resilience: "src/lib/failure-resilience",
  trust_provenance: "src/lib/trust-provenance",
  network_effect_moat: "src/lib/network-effect-moat",
  success_model: "src/lib/success-model",
  final_output_contract: "src/lib/final-output-contract",
  mvp_surface_area: "src/lib/mvp-surface-area",
  continuous_execution_loop: "src/lib/continuous-execution-loop",
  behavior_interpretation_engine: "src/lib/behavior-interpretation-engine",
  continuity_decay_engine: "src/lib/continuity-decay-engine",
  north_star_experience: "src/lib/north-star-experience",
  architectural_boundaries: "src/lib/architectural-boundaries",
  clarification_engine: "src/lib/clarification-engine",
  memory_strategy_engine: "src/lib/memory-strategy-engine",
  trust_layer_engine: "src/lib/trust-layer-engine",
  crisis_mode_interaction_layer: "src/lib/crisis-mode-interaction-layer",
  multi_caregiver_context_model: "src/lib/multi-caregiver-context-model",
  audit_trail_system: "src/lib/audit-trail-system",
  state_of_care_summary_engine: "src/lib/state-of-care-summary-engine",
  care_context_diff_engine: "src/lib/care-context-diff-engine",
  entry_behavior_protocol: "src/lib/entry-behavior-protocol",
  care_timeline_engine: "src/lib/care-timeline-engine",
  task_extraction_system: "src/lib/task-extraction-engine",
  current_state_view_engine: "src/lib/current-state-view-engine",
  forbidden_build_zone: "src/lib/forbidden-build-zone",
  adoption_wedge_engine: "src/lib/adoption-wedge-engine",
  product_reality_model: "src/lib/product-reality-model",
  policy_engine: "src/lib/policy-engine",
  contradiction_detection_engine: "src/lib/contradiction-detection-engine",
  timeline_reconstruction_engine: "src/lib/timeline-reconstruction-engine",
  care_transparency_layer: "src/lib/care-transparency-layer",
  baseline_intelligence_engine: "src/lib/baseline-intelligence-engine",
  care_reality_profile_engine: "src/lib/care-reality-profile-engine",
  moment_of_need_engine: "src/lib/moment-of-need-engine",
  retention_engine: "src/lib/retention-engine",
  priority_resolution_system: "src/lib/priority-resolution-system",
  event_sourced_storage: "src/lib/event-sourced-storage",
  engine_execution_contract: "src/lib/engine-execution-contract",
  edge_state_machine: "src/lib/edge-state-machine",
  confidence_calibration_system: "src/lib/confidence-calibration-system",
  care_state_engine: "src/lib/care-state-engine",
  single_user_journey: "src/lib/single-user-journey",
  product_north_star: "src/lib/product-north-star",
  product_constitution: "src/lib/product-constitution",
};

export const CARE_CONTINUITY_PIPELINE = [
  "Caregiver input or document",
  "Information completeness check",
  "Extract structured knowledge",
  "Create or update Continuity Graph nodes",
  "Detect relationships and dependencies",
  "Assess continuity intelligence",
  "Memory available for reconstruction",
  "Meeting preparation when scheduled",
] as const;
