/**
 * SolenOS 3-Layer Architecture
 * ============================
 * 🟢 STATE   — objective current reality (Situation + Demand + document refs)
 * 🟡 BELIEF  — unified uncertainty (assumption | missing_information)
 * 🔵 EXPLANATION — post-hoc Decision History + Timeline + health summary + Human Trust
 *
 * Derived (pure, non-persistent): computeRisk, computePriority (PriorityContract),
 * computeHealthSummary, computePressureScore, computeCaregiverLoad
 *
 * Runtime: INPUT → STATE UPDATE → BELIEF UPDATE → DERIVED → ACTION → EXPLANATION
 * Analyze: Decision Engine → HUMAN TRUST → Safety → trust/disclaimer Output
 */

export {
  SOLENOS_LAYERS_IDENTITY,
  SOLENOS_LAYERS_ONE_LINE_TRUTH,
  SOLENOS_LAYER_NAMES,
  SOLENOS_RUNTIME_PIPELINE,
  SOLENOS_LAYERS_FORBIDDEN,
  BELIEF_ITEM_TYPES,
  BELIEF_ITEM_STATUSES,
  BELIEF_IMPORTANCE,
  STATE_SITUATION_STATUSES,
  STATE_ACTION_STATUSES,
  STATE_PRIORITIES,
  HIGH_MISSING_INFO_CONFIDENCE_CAP,
  DEPRECATED_FACADE_NOTICE,
} from "./contract-constants";

export type {
  SolenosLayerName,
  SolenosRuntimeStage,
  StateSituation,
  StateSituationStatus,
  StateActionStatus,
  StatePriority,
  StateStoreSnapshot,
  BeliefItem,
  BeliefItemType,
  BeliefItemStatus,
  BeliefImportance,
  BeliefStoreSnapshot,
  ExplanationDecisionRecord,
  ExplanationTimelineEvent,
  ExplanationHealthSummary,
  DerivedRiskResult,
  DerivedPriorityResult,
  DerivedSituationPriorityScore,
  DerivedCaregiverLoadResult,
  DerivedConfidenceState,
  DerivedCrisisRisk,
  DerivedDelegationSuggestion,
  LayeredRuntimeResult,
} from "./types";

export {
  mapLifecycleToStateStatus,
  mapStateStatusToLifecycle,
  toStateSituation,
  isOperationallyActive,
  resetStateStore,
  listStateSituations,
  listStateSituationsForUser,
  listActiveStateSituations,
  upsertStateSituation,
  replaceStateSituations,
  getStateSituation,
  attachDocumentRefs,
  getStateSnapshot,
  listAllStateSituations,
  resetDemandStore,
  listDemands,
  listActiveDemands,
  getDemand,
  upsertDemand,
  mergeGeneratedDemands,
  replaceDemands,
  transitionDemandStatus,
  canTransitionDemand,
} from "./state";

export {
  createBeliefItem,
  mapAssumptionStatusToBelief,
  mapBeliefStatusToAssumption,
  mapMissingInfoStatusToBelief,
  mapBeliefStatusToMissingInfo,
  assumptionToBeliefItem,
  missingInfoToBeliefItem,
  resetBeliefStore,
  getBeliefSnapshot,
  setBeliefItems,
  listBeliefs,
  upsertBelief,
  addBelief,
  updateBeliefStatus,
  listActiveAssumptions,
  listActiveMissingInformation,
  hasHighImportanceMissingInformation,
  countHighImportanceMissingInformation,
  computeBeliefInfluence,
  type BeliefInfluenceEnvelope,
} from "./belief";

export {
  writeExplanationDecision,
  toExplanationDecision,
  writeDecisionHistory,
  getDecisionHistoryLog,
  setDecisionHistoryLog,
  createEmptyDecisionHistoryLog,
  decisionHistoryForSituation,
  resetDecisionHistoryStore,
  writeExplanationTimelineEvent,
  toExplanationTimelineEvent,
  createEmptyTimeline,
  timelineForSituation,
  appendTimelineEntry,
  viewHealthSummary,
  buildRecommendationExplanation,
  buildHumanTrustLayer,
  processHumanTrustLayer,
  toHumanTrustLayerPayload,
  challengeModeCompare,
  runHumanTrustGuarantee,
  HUMAN_TRUST_LAYER_PIPELINE_POSITION,
  type DecisionHistory,
  type WriteDecisionHistoryParams,
  type WriteTimelineEventParams,
  type TimelineEntry,
  type TimelineLog,
  type RecommendationExplanation,
  type DecisionExplanationContext,
  type HumanTrustLayerPayload,
  type HumanTrustLayerResult,
  type ChallengeComparison,
  type ReversibilityAffordance,
} from "./explanation";

export {
  computeRisk,
  computePriority,
  buildPriorityContractInputs,
  PriorityContract,
  calculatePriorityContract,
  rankByPriorityContract,
  calculateAndRankSituations,
  computeTimeDecayFactor,
  formatPriorityExplanation,
  riskLevelFromStatePriority,
  RISK_WEIGHT,
  TIME_URGENCY,
  COMPLETION_FACTOR,
  UNCERTAINTY_FIELD_COEFFICIENT,
  DEPENDENCY_SITUATION_COEFFICIENT,
  PRIORITY_CONTRACT_ONE_LINE,
  computeHealthSummary,
  computeAutonomyGate,
  computeCaregiverLoad,
  classifyLoadState,
  surfaceLimitForState,
  normalizeLoadScore,
  computeRawLoadScore,
  computePressureScore,
  withPressureScore,
  clampScore100,
  rankDemandsByPressure,
  selectTopPressureDemands,
  buildDemandEngineOutput,
  evaluateFailSafeTriggers,
  buildDecisionConfidence,
  computeConfidenceState,
  computeCrisisRisks,
  computeDelegationSuggestions,
  type ConfidenceState,
  type ComputeConfidenceInputs,
  type CrisisRisk,
  type CrisisCategory,
  type ComputeCrisisRisksInputs,
  type DelegationSuggestion,
  type ComputeDelegationInputs,
  type DecisionConfidence,
  type FailSafeModeInput,
  type FailSafeTriggerHit,
  type ComputePriorityParams,
  type PriorityDemandInput,
  type SituationPrioritySignal,
  type PriorityContractInput,
  type PriorityContractResult,
  type PriorityContractRankResult,
  type PriorityComponentBreakdown,
  type RiskLevel,
  type TimeUrgencyKey,
  type CompletionLevel,
  type CaregiverLoad,
  type CaregiverLoadInputs,
  type CaregiverLoadState,
  classifyTimeCurve,
  computeRiskOverTime,
  computeCurveTimeDecayFactor,
  type TimeCurveType,
  type TimeThresholds,
} from "./derived";

export {
  runLayeredPipeline,
  syncStateFromTrackedSituations,
  type LayeredPipelineInput,
} from "./pipeline";

export {
  syncTrackedSituationsToState,
  syncLegacyBeliefsToStore,
} from "./adapters";

export {
  LAYER_ARCHITECTURE_MAP,
  FACADE_DEPRECATION,
  SITUATION_ROOT_ENTITY,
  CASE_MEMORY_PRODUCT,
  V14_PRINCIPLES,
  V14_ENGINE_MODULES,
  V14_PIPELINE_SPEC_ORDER,
  V14_PIPELINE_ACTUAL_ORDER,
  V14_PIPELINE_NOTES,
  V14_GAP_STUBS,
  V14_ANTI_PATTERNS,
  V14_PRODUCT_NORTH_STAR,
  PRODUCT_MEMORY_NORTH_STAR,
  PRODUCT_CONSTITUTION,
  CONTINUITY_PROPERTIES,
  UNKNOWNS_AND_PROJECTION_LAYERS,
  BEHAVIORAL_SPEC_V1_IDENTITY,
  OBSERVATION_INTELLIGENCE_MVP,
  STRATEGIC_ARCHITECTURE,
  DOCUMENTATION_GOVERNANCE,
} from "./architecture-map";
