export {
  SOLENOS_PRODUCT_NAME,
  CARE_REALITY_INTELLIGENCE_CATEGORY_PHRASE,
  LIVING_CARE_RECORD_FOUNDATION,
  SOLENOS_PRODUCT_IDENTITY,
  SOLENOS_PHILOSOPHY_CHAIN,
  FORBIDDEN_PRODUCT_NAMES,
  FORBIDDEN_SOLENOS_DESCRIPTIONS,
} from "./contract-constants";
