export {
  createEpistemicFoundationEngine,
  type EpistemicFoundationEngine,
} from "./engine";

export {
  EPISTEMIC_FOUNDATION_IDENTITY,
  EPISTEMIC_FOUNDATION_DEFINING_PRINCIPLE,
  EVIDENCE_KINDS,
  EPISTEMIC_STATUSES,
  CLAIM_LIFECYCLE_STATUSES,
  INFERENCE_CONFIDENCE_DIMENSIONS,
  UNCERTAINTY_LEVELS,
  ABSENCE_MODELS,
  REASONING_TYPES,
  EPISTEMIC_RULES,
  EPISTEMIC_VIOLATIONS,
  FORMAL_RULES,
} from "./contract-constants";

export type {
  EvidenceKind,
  EpistemicStatus,
  ClaimLifecycleStatus,
  InferenceConfidenceDimension,
  UncertaintyLevel,
  AbsenceModel,
  ReasoningType,
  EpistemicRule,
  EpistemicViolation,
  FormalRule,
  EvidenceItem,
  EvidenceSource,
  Claim,
  Inference,
  InferenceConfidence,
  InferenceInput,
  ClaimProvenance,
  DerivationStep,
  ContradictionRecord,
  KnowledgeRevisionEntry,
  UnknownState,
  AssumptionRecord,
  EpistemicViolationRecord,
  EpistemicFoundationQuery,
  EpistemicFoundationResult,
  ClaimTraceResult,
  EvidenceToClaimTraceResult,
  InferenceValidationResult,
} from "./types";
