import type { ClinicalUnknownsProfile, UnknownProfileRule } from "../types";

/**
 * Dementia clinical profile — MVP unknown categories.
 * Loaded by the Unknowns Engine; swapping profiles does not change the engine.
 */
export const DEMENTIA_UNKNOWNS_PROFILE: ClinicalUnknownsProfile = {
  profile_id: "dementia",
  label: "Dementia caregiving (MVP)",
  condition_label: "dementia",
  important_observation_signals: [
    "appetite",
    "hydration",
    "medication",
    "sleep",
    "wandering",
    "falls",
    "agitation",
    "hallucination",
    "continence",
    "mobility",
    "confusion",
    "communication",
    "adl",
    "caregiver_stress",
    "hospital",
    "appointment",
  ],
  rules: [
    {
      category: "nutrition",
      missing_information: "current_weight_trend",
      trigger_pattern: /\b(appetite|eating|meal|not eating|weight)\b/i,
      resolved_pattern: /\b(weigh(?:ed|t)|lbs?|kg)\b/i,
      reason_it_matters: "Needed to assess nutritional decline",
      clinical_or_operational_impact: "Impacts risk evaluation for deterioration",
      priority: "high",
      confidence_impact: "material",
      clarification_question:
        "Has there been a recent weight check, or noticeable weight change?",
    },
    {
      category: "hydration",
      missing_information: "hydration_status",
      // Narrow clinical trigger only — never confuse/fatigue → drink quiz.
      trigger_pattern: /\b(dehydrat|not drinking|won't drink|refusing fluids)\b/i,
      resolved_pattern: /\b(water|hydrat|fluid intake|drinking)\b/i,
      reason_it_matters: "Needed when fluid refusal is explicitly reported",
      clinical_or_operational_impact: "Impacts care urgency classification",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "What else have you noticed alongside this?",
    },
    {
      category: "medication",
      missing_information: "medication_adherence",
      trigger_pattern: /\b(med(?:ication|s)?|dose|pill|pharmacy)\b/i,
      resolved_pattern: /\b(took|missed|adherence|as prescribed|refill)\b/i,
      reason_it_matters: "Needed to determine if behavior change is medically driven",
      clinical_or_operational_impact: "Impacts accuracy of progression inference",
      priority: "critical",
      confidence_impact: "blocks_recommendation",
      clarification_question:
        "Since the last medication change or hospital visit, have doses been taken as prescribed?",
    },
    {
      category: "sleep",
      missing_information: "sleep_pattern_detail",
      trigger_pattern: /\b(sleep|night|insomnia|waking)\b/i,
      resolved_pattern: /\b(hours of sleep|slept \d)\b/i,
      reason_it_matters: "Sleep disruption often co-travels with nighttime risk",
      clinical_or_operational_impact: "Improves nighttime risk and load estimates",
      priority: "medium",
      confidence_impact: "improves_confidence",
      clarification_question: "How many hours of overnight sleep has been typical this week?",
    },
    {
      category: "wandering",
      missing_information: "wandering_frequency",
      trigger_pattern: /\b(wander|elop|got (?:out|away)|exit.?seek)\b/i,
      resolved_pattern: /\b(times? (?:this|last) week|every night|frequency)\b/i,
      reason_it_matters: "Frequency distinguishes isolated incident from rising risk",
      clinical_or_operational_impact: "Impacts supervision and Diff weighting",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "How many wandering or exit-seeking episodes happened this week?",
    },
    {
      category: "falls",
      missing_information: "fall_circumstances",
      trigger_pattern: /\b(fell|fall|almost fell|tripped)\b/i,
      // Evidence tokens only — never fall→head product Q&A for caregivers
      resolved_pattern: /\b(with walker|unwitnessed|injury|circumstances)\b/i,
      reason_it_matters: "Circumstances change urgency and medical follow-up",
      clinical_or_operational_impact: "Impacts attention priority and clinician handoff",
      priority: "high",
      confidence_impact: "material",
      // Generic gap ask — never fall→head keyword product template for caregivers
      clarification_question: "What else do you know about what happened around this?",
    },
    {
      category: "behavior",
      missing_information: "agitation_triggers",
      trigger_pattern: /\b(agitat|aggress|combative|resist(?:ed|ing)? care)\b/i,
      reason_it_matters: "Triggers guide non-drug calming approaches in Care Memory",
      clinical_or_operational_impact: "Improves operational continuity and load",
      priority: "medium",
      confidence_impact: "improves_confidence",
      clarification_question: "What was happening just before the agitation (time, place, people)?",
    },
    {
      category: "perception",
      missing_information: "hallucination_context",
      trigger_pattern: /\b(hallucin|delusion|seeing things|paranoid)\b/i,
      reason_it_matters: "New perceptual changes need clinical context, not diagnosis by SolenOS",
      clinical_or_operational_impact: "Flags clinician conversation priority",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "When did the unusual perceptions start relative to any medication change?",
    },
    {
      category: "continence",
      missing_information: "continence_change_detail",
      trigger_pattern: /\b(incontin|toileting|accident|wet(ting)?)\b/i,
      reason_it_matters: "Continence shifts often signal infection or progression",
      clinical_or_operational_impact: "Affects urgency and daily care planning",
      priority: "medium",
      confidence_impact: "improves_confidence",
      clarification_question: "Is this a new continence change, and over what timeframe?",
    },
    {
      category: "mobility",
      missing_information: "mobility_baseline",
      trigger_pattern: /\b(fell|fall|mobility|walker|unsteady|gait)\b/i,
      resolved_pattern: /\b(independent|uses walker|wheelchair|baseline)\b/i,
      reason_it_matters: "Needed to compare against previous mobility state",
      clinical_or_operational_impact: "Impacts progression visibility",
      priority: "medium",
      confidence_impact: "improves_confidence",
      clarification_question: "Compared with a month ago, is walking more assisted, the same, or less?",
    },
    {
      category: "cognition",
      missing_information: "cognitive_change_onset",
      trigger_pattern: /\b(confus|disorient|memory|cognit)\b/i,
      resolved_pattern: /\b(yesterday|this week|since|started)\b/i,
      reason_it_matters: "Onset timing separates gradual progression from acute change",
      clinical_or_operational_impact: "Guides Diff Engine and clinical prep",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "When did you first notice this confusion relative to other recent changes?",
    },
    {
      category: "function",
      missing_information: "adl_support_level",
      trigger_pattern: /\b(dress|bath|toilet|meal prep|adl|i.?adl|daily living)\b/i,
      reason_it_matters: "Function level frames supervision and care capacity",
      clinical_or_operational_impact: "Improves State of Care and load estimates",
      priority: "medium",
      confidence_impact: "improves_confidence",
      clarification_question: "Which daily tasks now need more help than a month ago?",
    },
    {
      category: "caregiver_load",
      missing_information: "caregiver_stress_signals",
      trigger_pattern: /\b(overwhelm|exhaust|burnout|can't sleep|guilt)\b/i,
      reason_it_matters: "Load is part of care reality, not a side concern",
      clinical_or_operational_impact: "Feeds Caregiver Load and attention budget",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "In the last week, how often have you felt unable to keep up safely?",
    },
    {
      category: "clinical_events",
      missing_information: "hospital_discharge_follow_up",
      trigger_pattern: /\b(hospital|discharge|admitted|ER|emergency)\b/i,
      resolved_pattern: /\b(follow[- ]?up (?:done|booked|scheduled)|saw (?:the )?doctor)\b/i,
      reason_it_matters: "Post-discharge gaps drive missed continuity",
      clinical_or_operational_impact: "Critical for Diff and attention",
      priority: "critical",
      confidence_impact: "blocks_recommendation",
      clarification_question: "Has the post-discharge follow-up appointment been scheduled or completed?",
    },
    {
      category: "medications",
      missing_information: "recent_medication_change_detail",
      trigger_pattern: /\b(med(?:ication)? (?:chang|increas|decreas|stopp|start)|new (?:pill|rx))\b/i,
      resolved_pattern: /\b(started on|dose (?:is|of)|mg)\b/i,
      reason_it_matters: "Medication changes anchor progression explanations",
      clinical_or_operational_impact: "Required for evidence-linked Diff",
      priority: "high",
      confidence_impact: "material",
      clarification_question: "What medication changed, and on approximately which date?",
    },
    {
      category: "appointments",
      missing_information: "upcoming_appointment",
      trigger_pattern: /\b(appoint|neurolog|geriatr|clinic|follow[- ]?up)\b/i,
      resolved_pattern: /\b(on (?:monday|tuesday|wednesday|thursday|friday|\d)|scheduled for)\b/i,
      reason_it_matters: "Upcoming visits are the moment Continuity pays off",
      clinical_or_operational_impact: "Enables meeting preparation and 10-minute priorities",
      priority: "low",
      confidence_impact: "informational",
      clarification_question: "Is there an upcoming appointment we should prepare changes for?",
    },
  ] as const satisfies readonly UnknownProfileRule[],
};
