export {
  FAILURE_STAGES,
  FAILURE_TYPES,
  FailureLogEntrySchema,
  fingerprintOutput,
  fingerprintsDiverge,
} from "./types";
export type {
  FailureStage,
  FailureType,
  FailureLogEntry,
  OutputFingerprint,
} from "./types";
export {
  FailureObservabilityCollector,
  peekLastFailureLogs,
  publishLastFailureLogs,
  clearLastFailureLogs,
} from "./collector";
export {
  detectInputOverload,
  classifyParseFailure,
  classifyZodFailure,
  classifyQualityFailure,
  classifyOverloadFailure,
  classifyInferenceInconsistency,
  classifyConsistencyFailure,
  classifyPromptRegressionFailure,
  classifyStructureDriftFailure,
  classifyOutputStabilityFailure,
  classifyPriorityDriftFailure,
  classifyInterpretationDriftFailure,
  classifyMedicalBoundaryFailure,
  classifyEpistemicSafetyFailure,
  classifyGroundingFailure,
  classifyUnknownStateFailure,
  classifyEmotionalStabilizationFailure,
  classifyDocumentIntakeFailure,
  classifyCalibratedUncertaintyFailure,
  classifyCognitiveClarityFailure,
  classifyUrgencyEscalationFailure,
  classifySafetyOverrideFailure,
  classifyNonConversationalFailure,
  classifyNonAssistantOutputFailure,
  classifyEpisodicReliefFailure,
  classifyChaosToClarityFailure,
  classifySemanticRoleIsolationFailure,
  classifyOutputCompressionFailure,
  classifyPressureReductionFailure,
  classifyCognitiveCompressionFailure,
  classifyClarityGateBlockFailure,
  classifyDeterminismFailure,
} from "./classify";
